// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using comara.Data;

#nullable disable

namespace comara.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251022013212_AddVentaTipoEstadoAndMetodoPago")]
    partial class AddVentaTipoEstadoAndMetodoPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("comara.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Activo")
                        .HasColumnType("bytea")
                        .HasColumnName("activo");

                    b.Property<string>("ArtAlt1")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("artAlt1");

                    b.Property<string>("ArtAlt2")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("artAlt2");

                    b.Property<int>("ArtCod")
                        .HasColumnType("integer")
                        .HasColumnName("artCod");

                    b.Property<decimal?>("ArtCost")
                        .HasColumnType("numeric")
                        .HasColumnName("artCosto");

                    b.Property<string>("ArtDesc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("artDesc");

                    b.Property<bool?>("ArtExist")
                        .HasColumnType("boolean")
                        .HasColumnName("artExist");

                    b.Property<float?>("ArtL1")
                        .HasColumnType("real")
                        .HasColumnName("artL1");

                    b.Property<float?>("ArtL2")
                        .HasColumnType("real")
                        .HasColumnName("artL2");

                    b.Property<float?>("ArtL3")
                        .HasColumnType("real")
                        .HasColumnName("artL3");

                    b.Property<float?>("ArtL4")
                        .HasColumnType("real")
                        .HasColumnName("artL4");

                    b.Property<float?>("ArtL5")
                        .HasColumnType("real")
                        .HasColumnName("artL5");

                    b.Property<float?>("ArtStock")
                        .HasColumnType("real")
                        .HasColumnName("artStock");

                    b.Property<float?>("ArtStockMin")
                        .HasColumnType("real")
                        .HasColumnName("artStockMin");

                    b.Property<int>("ArtUni")
                        .HasColumnType("integer")
                        .HasColumnName("artUni");

                    b.Property<int>("IvaCod")
                        .HasColumnType("integer")
                        .HasColumnName("ivaCod");

                    b.Property<int>("MarCod")
                        .HasColumnType("integer")
                        .HasColumnName("marCod");

                    b.Property<int>("ProCod")
                        .HasColumnType("integer")
                        .HasColumnName("proCod");

                    b.Property<int>("RubCod")
                        .HasColumnType("integer")
                        .HasColumnName("rubCod");

                    b.Property<int>("SrubCod")
                        .HasColumnType("integer")
                        .HasColumnName("srubCod");

                    b.HasKey("Id");

                    b.HasIndex("ArtCod")
                        .IsUnique();

                    b.HasIndex("IvaCod");

                    b.HasIndex("MarCod");

                    b.HasIndex("ProCod");

                    b.ToTable("ARTICULOS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CliCUIT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliCUIT");

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliDireccion");

                    b.Property<string>("CliEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliEmail");

                    b.Property<string>("CliNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliNombre");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliTelefono");

                    b.HasKey("Id");

                    b.HasIndex("CliCod")
                        .IsUnique();

                    b.ToTable("CLIENTES", (string)null);
                });

            modelBuilder.Entity("comara.Models.Cobro", b =>
                {
                    b.Property<int>("CobCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cobCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CobCod"));

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<DateTime>("CobFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cobFech");

                    b.Property<string>("CobMetodo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cobMetodo");

                    b.Property<float>("CobMonto")
                        .HasColumnType("real")
                        .HasColumnName("cobMonto");

                    b.HasKey("CobCod");

                    b.HasIndex("CliCod");

                    b.ToTable("COBROS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Cotizacion", b =>
                {
                    b.Property<int>("CotCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cotCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CotCod"));

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<string>("CotEstado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cotEstado");

                    b.Property<DateTime>("CotFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cotFech");

                    b.Property<float>("CotTotal")
                        .HasColumnType("real")
                        .HasColumnName("cotTotal");

                    b.HasKey("CotCod");

                    b.HasIndex("CliCod");

                    b.ToTable("COTIZACIONES", (string)null);
                });

            modelBuilder.Entity("comara.Models.CuentaCorriente", b =>
                {
                    b.Property<int>("CctaCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cctaCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CctaCod"));

                    b.Property<string>("CctaDesc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cctaDesc");

                    b.Property<DateTime>("CctaFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cctaFech");

                    b.Property<float>("CctaMonto")
                        .HasColumnType("real")
                        .HasColumnName("cctaMonto");

                    b.Property<string>("CctaMovimiento")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cctaMovimiento");

                    b.Property<float>("CctaSaldo")
                        .HasColumnType("real")
                        .HasColumnName("cctaSaldo");

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.HasKey("CctaCod");

                    b.HasIndex("CliCod");

                    b.ToTable("CUENTAS_CORRIENTES", (string)null);
                });

            modelBuilder.Entity("comara.Models.DetalleCotizacion", b =>
                {
                    b.Property<int>("DetCotCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detCotCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetCotCod"));

                    b.Property<int>("ArtCod")
                        .HasColumnType("integer")
                        .HasColumnName("artCod");

                    b.Property<int>("CotCod")
                        .HasColumnType("integer")
                        .HasColumnName("cotCod");

                    b.Property<float>("DetCant")
                        .HasColumnType("real")
                        .HasColumnName("detCant");

                    b.Property<float>("DetPrecio")
                        .HasColumnType("real")
                        .HasColumnName("detPrecio");

                    b.Property<float>("DetSubtotal")
                        .HasColumnType("real")
                        .HasColumnName("detSubtotal");

                    b.HasKey("DetCotCod");

                    b.HasIndex("ArtCod");

                    b.HasIndex("CotCod");

                    b.ToTable("DETALLE_COTIZACIONES", (string)null);
                });

            modelBuilder.Entity("comara.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetCod"));

                    b.Property<int>("ArtCod")
                        .HasColumnType("integer")
                        .HasColumnName("artCod");

                    b.Property<float>("DetCant")
                        .HasColumnType("real")
                        .HasColumnName("detCant");

                    b.Property<float>("DetPrecio")
                        .HasColumnType("real")
                        .HasColumnName("detPrecio");

                    b.Property<float>("DetSubtotal")
                        .HasColumnType("real")
                        .HasColumnName("detSubtotal");

                    b.Property<int>("VenCod")
                        .HasColumnType("integer")
                        .HasColumnName("venCod");

                    b.HasKey("DetCod");

                    b.HasIndex("ArtCod");

                    b.HasIndex("VenCod");

                    b.ToTable("DETALLE_VENTAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Iva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("porcentaje");

                    b.HasKey("Id");

                    b.ToTable("IVA", (string)null);
                });

            modelBuilder.Entity("comara.Models.Lista", b =>
                {
                    b.Property<int>("ListCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("listCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListCode"));

                    b.Property<string>("ListDesc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("listDesc");

                    b.Property<float>("ListPercent")
                        .HasColumnType("real")
                        .HasColumnName("listPercent");

                    b.Property<bool>("ListStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("listStatus");

                    b.HasKey("ListCode");

                    b.ToTable("LISTAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Marca", b =>
                {
                    b.Property<int>("marCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("marCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("marCod"));

                    b.Property<string>("marNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marNombre");

                    b.HasKey("marCod");

                    b.ToTable("MARCAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Proveedor", b =>
                {
                    b.Property<int>("proCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("proCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("proCod"));

                    b.Property<string>("proCUIT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proCUIT");

                    b.Property<string>("proContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proContacto");

                    b.Property<string>("proNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proNombre");

                    b.HasKey("proCod");

                    b.ToTable("PROVEEDORES", (string)null);
                });

            modelBuilder.Entity("comara.Models.Venta", b =>
                {
                    b.Property<int>("VenCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("venCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenCod"));

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<int?>("VenEstado")
                        .HasColumnType("integer")
                        .HasColumnName("venEstado");

                    b.Property<DateTime>("VenFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("venFech");

                    b.Property<int?>("VenMetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("venMetodoPago");

                    b.Property<int?>("VenTipoCbte")
                        .HasColumnType("integer")
                        .HasColumnName("venTipoCbte");

                    b.Property<float>("VenTotal")
                        .HasColumnType("real")
                        .HasColumnName("venTotal");

                    b.HasKey("VenCod");

                    b.HasIndex("CliCod");

                    b.HasIndex("VenEstado");

                    b.HasIndex("VenMetodoPago");

                    b.ToTable("VENTAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.VentaTipoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("ventaTipoEstado", (string)null);
                });

            modelBuilder.Entity("comara.Models.VentaTipoMetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("ventaTipoMetodoPagos", (string)null);
                });

            modelBuilder.Entity("comara.Models.Articulo", b =>
                {
                    b.HasOne("comara.Models.Iva", "Iva")
                        .WithMany()
                        .HasForeignKey("IvaCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iva");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("comara.Models.Cobro", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("comara.Models.Cotizacion", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .HasPrincipalKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("comara.Models.CuentaCorriente", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("comara.Models.DetalleCotizacion", b =>
                {
                    b.HasOne("comara.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArtCod")
                        .HasPrincipalKey("ArtCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Cotizacion", "Cotizacion")
                        .WithMany("DetalleCotizaciones")
                        .HasForeignKey("CotCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("comara.Models.DetalleVenta", b =>
                {
                    b.HasOne("comara.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArtCod")
                        .HasPrincipalKey("ArtCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VenCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("comara.Models.Venta", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .HasPrincipalKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.VentaTipoEstado", "TipoEstado")
                        .WithMany()
                        .HasForeignKey("VenEstado");

                    b.HasOne("comara.Models.VentaTipoMetodoPago", "TipoMetodoPago")
                        .WithMany()
                        .HasForeignKey("VenMetodoPago");

                    b.Navigation("Cliente");

                    b.Navigation("TipoEstado");

                    b.Navigation("TipoMetodoPago");
                });

            modelBuilder.Entity("comara.Models.Cotizacion", b =>
                {
                    b.Navigation("DetalleCotizaciones");
                });

            modelBuilder.Entity("comara.Models.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
