// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using comara.Data;

#nullable disable

namespace comara.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220002451_AddUsuariosTable")]
    partial class AddUsuariosTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("comara.Models.AFIP.AfipAuthTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CuitRepresentado")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cuit_representado");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_time");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sign");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("CuitRepresentado", "Environment", "ExpirationTime")
                        .HasDatabaseName("idx_afip_tickets_expiration");

                    b.ToTable("afip_auth_tickets", (string)null);
                });

            modelBuilder.Entity("comara.Models.AfipLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CAE")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cae");

                    b.Property<int?>("DuracionMs")
                        .HasColumnType("integer")
                        .HasColumnName("duracionMs");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean")
                        .HasColumnName("exitoso");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ipAddress");

                    b.Property<string>("MensajeError")
                        .HasColumnType("text")
                        .HasColumnName("mensajeError");

                    b.Property<long?>("NumeroComprobante")
                        .HasColumnType("bigint")
                        .HasColumnName("numeroComprobante");

                    b.Property<int?>("PuntoVenta")
                        .HasColumnType("integer")
                        .HasColumnName("puntoVenta");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request");

                    b.Property<string>("Response")
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.Property<int?>("TipoComprobante")
                        .HasColumnType("integer")
                        .HasColumnName("tipoComprobante");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipoOperacion");

                    b.Property<int?>("VenCod")
                        .HasColumnType("integer")
                        .HasColumnName("venCod");

                    b.HasKey("Id");

                    b.HasIndex("VenCod");

                    b.ToTable("afipLogs", (string)null);
                });

            modelBuilder.Entity("comara.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Activo")
                        .HasColumnType("bytea")
                        .HasColumnName("activo");

                    b.Property<string>("ArtAlt1")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("artAlt1");

                    b.Property<string>("ArtAlt2")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("artAlt2");

                    b.Property<string>("ArtCod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("artCod");

                    b.Property<decimal?>("ArtCost")
                        .HasColumnType("numeric")
                        .HasColumnName("artCosto");

                    b.Property<string>("ArtDesc")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("artDesc");

                    b.Property<bool?>("ArtExist")
                        .HasColumnType("boolean")
                        .HasColumnName("artExist");

                    b.Property<float?>("ArtL1")
                        .HasColumnType("real")
                        .HasColumnName("artL1");

                    b.Property<float?>("ArtL2")
                        .HasColumnType("real")
                        .HasColumnName("artL2");

                    b.Property<float?>("ArtL3")
                        .HasColumnType("real")
                        .HasColumnName("artL3");

                    b.Property<float?>("ArtL4")
                        .HasColumnType("real")
                        .HasColumnName("artL4");

                    b.Property<float?>("ArtL5")
                        .HasColumnType("real")
                        .HasColumnName("artL5");

                    b.Property<float?>("ArtStock")
                        .HasColumnType("real")
                        .HasColumnName("artStock");

                    b.Property<float?>("ArtStockMin")
                        .HasColumnType("real")
                        .HasColumnName("artStockMin");

                    b.Property<int>("ArtUni")
                        .HasColumnType("integer")
                        .HasColumnName("artUni");

                    b.Property<int>("IvaCod")
                        .HasColumnType("integer")
                        .HasColumnName("ivaCod");

                    b.Property<int>("MarCod")
                        .HasColumnType("integer")
                        .HasColumnName("marCod");

                    b.Property<int>("ProCod")
                        .HasColumnType("integer")
                        .HasColumnName("proCod");

                    b.Property<int>("RubCod")
                        .HasColumnType("integer")
                        .HasColumnName("rubCod");

                    b.Property<int>("SrubCod")
                        .HasColumnType("integer")
                        .HasColumnName("srubCod");

                    b.HasKey("Id");

                    b.HasIndex("ArtCod")
                        .IsUnique();

                    b.HasIndex("IvaCod");

                    b.HasIndex("MarCod");

                    b.HasIndex("ProCod");

                    b.ToTable("ARTICULOS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Cheque", b =>
                {
                    b.Property<int>("ChqCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chqCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChqCod"));

                    b.Property<string>("ChqBanco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chqBanco");

                    b.Property<string>("ChqCUIT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("chqCUIT");

                    b.Property<bool>("ChqEnCaja")
                        .HasColumnType("boolean")
                        .HasColumnName("chqEnCaja");

                    b.Property<DateTime>("ChqFechaCobro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chqFechaCobro");

                    b.Property<DateTime>("ChqFechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chqFechaEmision");

                    b.Property<DateTime?>("ChqFechaSalida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chqFechaSalida");

                    b.Property<string>("ChqLibrador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chqLibrador");

                    b.Property<float>("ChqMonto")
                        .HasColumnType("real")
                        .HasColumnName("chqMonto");

                    b.Property<string>("ChqNumero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("chqNumero");

                    b.Property<string>("ChqObservaciones")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("chqObservaciones");

                    b.Property<int>("PagCod")
                        .HasColumnType("integer")
                        .HasColumnName("pagCod");

                    b.HasKey("ChqCod");

                    b.HasIndex("PagCod");

                    b.ToTable("CHEQUES", (string)null);
                });

            modelBuilder.Entity("comara.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CliCondicionIVA")
                        .HasColumnType("integer")
                        .HasColumnName("cliCondicionIVA");

                    b.Property<string>("CliDireccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliDireccion");

                    b.Property<string>("CliEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliEmail");

                    b.Property<int?>("CliFormaPago")
                        .HasColumnType("integer")
                        .HasColumnName("cliFormaPago");

                    b.Property<string>("CliNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliNombre");

                    b.Property<string>("CliNumDoc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliNumDoc");

                    b.Property<string>("CliTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliTelefono");

                    b.Property<int?>("CliTipoDoc")
                        .HasColumnType("integer")
                        .HasColumnName("cliTipoDoc");

                    b.HasKey("Id");

                    b.HasIndex("CliCondicionIVA");

                    b.HasIndex("CliFormaPago");

                    b.HasIndex("CliTipoDoc");

                    b.ToTable("CLIENTES", (string)null);
                });

            modelBuilder.Entity("comara.Models.ClienteTipoFormaPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("clienteTipoFormaPago", (string)null);
                });

            modelBuilder.Entity("comara.Models.Cobro", b =>
                {
                    b.Property<int>("CobCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cobCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CobCod"));

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<DateTime>("CobFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cobFech");

                    b.Property<string>("CobMetodo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cobMetodo");

                    b.Property<float>("CobMonto")
                        .HasColumnType("real")
                        .HasColumnName("cobMonto");

                    b.HasKey("CobCod");

                    b.HasIndex("CliCod");

                    b.ToTable("COBROS", (string)null);
                });

            modelBuilder.Entity("comara.Models.CondicionIVA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("integer")
                        .HasColumnName("codigoAfip");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("condicionIVA", (string)null);
                });

            modelBuilder.Entity("comara.Models.Cotizacion", b =>
                {
                    b.Property<int>("CotCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cotCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CotCod"));

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<string>("CotEstado")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cotEstado");

                    b.Property<DateTime>("CotFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cotFech");

                    b.Property<float>("CotTotal")
                        .HasColumnType("real")
                        .HasColumnName("cotTotal");

                    b.HasKey("CotCod");

                    b.HasIndex("CliCod");

                    b.ToTable("COTIZACIONES", (string)null);
                });

            modelBuilder.Entity("comara.Models.CuentaCorriente", b =>
                {
                    b.Property<int>("CctaCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cctaCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CctaCod"));

                    b.Property<string>("CctaDesc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cctaDesc");

                    b.Property<DateTime>("CctaFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cctaFech");

                    b.Property<float>("CctaMonto")
                        .HasColumnType("real")
                        .HasColumnName("cctaMonto");

                    b.Property<string>("CctaMovimiento")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cctaMovimiento");

                    b.Property<float>("CctaSaldo")
                        .HasColumnType("real")
                        .HasColumnName("cctaSaldo");

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.HasKey("CctaCod");

                    b.HasIndex("CliCod");

                    b.ToTable("CUENTAS_CORRIENTES", (string)null);
                });

            modelBuilder.Entity("comara.Models.DetalleCotizacion", b =>
                {
                    b.Property<int>("DetCotCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detCotCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetCotCod"));

                    b.Property<int>("ArtCod")
                        .HasColumnType("integer")
                        .HasColumnName("artCod");

                    b.Property<int>("CotCod")
                        .HasColumnType("integer")
                        .HasColumnName("cotCod");

                    b.Property<float>("DetCant")
                        .HasColumnType("real")
                        .HasColumnName("detCant");

                    b.Property<float>("DetPrecio")
                        .HasColumnType("real")
                        .HasColumnName("detPrecio");

                    b.Property<float>("DetSubtotal")
                        .HasColumnType("real")
                        .HasColumnName("detSubtotal");

                    b.HasKey("DetCotCod");

                    b.HasIndex("ArtCod");

                    b.HasIndex("CotCod");

                    b.ToTable("DETALLE_COTIZACIONES", (string)null);
                });

            modelBuilder.Entity("comara.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("detCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DetCod"));

                    b.Property<int>("ArtCod")
                        .HasColumnType("integer")
                        .HasColumnName("artCod");

                    b.Property<float>("DetCant")
                        .HasColumnType("real")
                        .HasColumnName("detCant");

                    b.Property<float>("DetPrecio")
                        .HasColumnType("real")
                        .HasColumnName("detPrecio");

                    b.Property<float>("DetSubtotal")
                        .HasColumnType("real")
                        .HasColumnName("detSubtotal");

                    b.Property<int>("VenCod")
                        .HasColumnType("integer")
                        .HasColumnName("venCod");

                    b.HasKey("DetCod");

                    b.HasIndex("ArtCod");

                    b.HasIndex("VenCod");

                    b.ToTable("DETALLE_VENTAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Iva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Porcentaje")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("porcentaje");

                    b.HasKey("Id");

                    b.ToTable("IVA", (string)null);
                });

            modelBuilder.Entity("comara.Models.Lista", b =>
                {
                    b.Property<int>("ListCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("listCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ListCode"));

                    b.Property<string>("ListDesc")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("listDesc");

                    b.Property<float>("ListPercent")
                        .HasColumnType("real")
                        .HasColumnName("listPercent");

                    b.Property<bool>("ListStatus")
                        .HasColumnType("boolean")
                        .HasColumnName("listStatus");

                    b.HasKey("ListCode");

                    b.ToTable("LISTAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Marca", b =>
                {
                    b.Property<int>("marCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("marCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("marCod"));

                    b.Property<string>("marNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marNombre");

                    b.HasKey("marCod");

                    b.ToTable("MARCAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.MovimientoCaja", b =>
                {
                    b.Property<int>("MovCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("movCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovCod"));

                    b.Property<int?>("ChqCod")
                        .HasColumnType("integer")
                        .HasColumnName("chqCod");

                    b.Property<string>("MovDescripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("movDescripcion");

                    b.Property<DateTime>("MovFecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("movFecha");

                    b.Property<int>("MovMetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("movMetodoPago");

                    b.Property<float>("MovMonto")
                        .HasColumnType("real")
                        .HasColumnName("movMonto");

                    b.Property<int>("MovTipo")
                        .HasColumnType("integer")
                        .HasColumnName("movTipo");

                    b.HasKey("MovCod");

                    b.HasIndex("ChqCod");

                    b.HasIndex("MovMetodoPago");

                    b.HasIndex("MovTipo");

                    b.ToTable("MOVIMIENTOS_CAJA", (string)null);
                });

            modelBuilder.Entity("comara.Models.Pago", b =>
                {
                    b.Property<int>("PagCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pagCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagCod"));

                    b.Property<int?>("CctaCod")
                        .HasColumnType("integer")
                        .HasColumnName("cctaCod");

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<string>("PagDesc")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pagDesc");

                    b.Property<DateTime>("PagFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pagFech");

                    b.Property<int>("PagMetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("pagMetodoPago");

                    b.Property<float>("PagMonto")
                        .HasColumnType("real")
                        .HasColumnName("pagMonto");

                    b.HasKey("PagCod");

                    b.HasIndex("CctaCod");

                    b.HasIndex("CliCod");

                    b.HasIndex("PagMetodoPago");

                    b.ToTable("PAGOS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Proveedor", b =>
                {
                    b.Property<int>("proCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("proCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("proCod"));

                    b.Property<string>("proCUIT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proCUIT");

                    b.Property<string>("proCelular")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("proCelular");

                    b.Property<string>("proContacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proContacto");

                    b.Property<decimal?>("proDescuento")
                        .HasColumnType("numeric")
                        .HasColumnName("proDescuento");

                    b.Property<string>("proEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proEmail");

                    b.Property<string>("proNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("proNombre");

                    b.HasKey("proCod");

                    b.ToTable("PROVEEDORES", (string)null);
                });

            modelBuilder.Entity("comara.Models.TipoComprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("integer")
                        .HasColumnName("codigoAfip");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("RequiereCAE")
                        .HasColumnType("boolean")
                        .HasColumnName("requiereCAE");

                    b.HasKey("Id");

                    b.ToTable("tipoComprobante", (string)null);
                });

            modelBuilder.Entity("comara.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoAfip")
                        .HasColumnType("integer")
                        .HasColumnName("codigoAfip");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("tipoDocumento", (string)null);
                });

            modelBuilder.Entity("comara.Models.TipoMovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("tipoMovimientoCaja", (string)null);
                });

            modelBuilder.Entity("comara.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("UsuActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("usuActivo");

                    b.Property<int?>("UsuCreadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("usuCreadoPor");

                    b.Property<string>("UsuEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuEmail");

                    b.Property<DateTime>("UsuFechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usuFechaCreacion");

                    b.Property<DateTime?>("UsuFechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usuFechaModificacion");

                    b.Property<int?>("UsuModificadoPor")
                        .HasColumnType("integer")
                        .HasColumnName("usuModificadoPor");

                    b.Property<string>("UsuNombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usuNombreCompleto");

                    b.Property<string>("UsuPasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("usuPasswordHash");

                    b.Property<string>("UsuRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("usuRole");

                    b.Property<DateTime?>("UsuUltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usuUltimoLogin");

                    b.Property<string>("UsuUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usuUsername");

                    b.HasKey("Id");

                    b.HasIndex("UsuActivo");

                    b.HasIndex("UsuCreadoPor");

                    b.HasIndex("UsuRole");

                    b.HasIndex("UsuUsername")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("comara.Models.Venta", b =>
                {
                    b.Property<int>("VenCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("venCod");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenCod"));

                    b.Property<int>("CliCod")
                        .HasColumnType("integer")
                        .HasColumnName("cliCod");

                    b.Property<string>("VenCAE")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("venCAE");

                    b.Property<DateTime?>("VenCAEVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("venCAEVencimiento");

                    b.Property<int?>("VenEstado")
                        .HasColumnType("integer")
                        .HasColumnName("venEstado");

                    b.Property<DateTime>("VenFech")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("venFech");

                    b.Property<DateTime?>("VenFechVenta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("venFechVenta");

                    b.Property<DateTime?>("VenFechaAutorizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("venFechaAutorizacion");

                    b.Property<int?>("VenLista")
                        .HasColumnType("integer")
                        .HasColumnName("venLista");

                    b.Property<int?>("VenMetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("venMetodoPago");

                    b.Property<long?>("VenNumComprobante")
                        .HasColumnType("bigint")
                        .HasColumnName("venNumComprobante");

                    b.Property<string>("VenObservacionesAfip")
                        .HasColumnType("text")
                        .HasColumnName("venObservacionesAfip");

                    b.Property<int?>("VenPuntoVenta")
                        .HasColumnType("integer")
                        .HasColumnName("venPuntoVenta");

                    b.Property<string>("VenResultadoAfip")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("venResultadoAfip");

                    b.Property<int?>("VenTipoCbte")
                        .HasColumnType("integer")
                        .HasColumnName("venTipoCbte");

                    b.Property<float>("VenTotal")
                        .HasColumnType("real")
                        .HasColumnName("venTotal");

                    b.HasKey("VenCod");

                    b.HasIndex("CliCod");

                    b.HasIndex("VenEstado");

                    b.HasIndex("VenLista");

                    b.HasIndex("VenMetodoPago");

                    b.HasIndex("VenTipoCbte");

                    b.ToTable("VENTAS", (string)null);
                });

            modelBuilder.Entity("comara.Models.VentaTipoEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("ventaTipoEstado", (string)null);
                });

            modelBuilder.Entity("comara.Models.VentaTipoMetodoPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id");

                    b.ToTable("ventaTipoMetodoPagos", (string)null);
                });

            modelBuilder.Entity("comara.Models.AfipLog", b =>
                {
                    b.HasOne("comara.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("VenCod")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("comara.Models.Articulo", b =>
                {
                    b.HasOne("comara.Models.Iva", "Iva")
                        .WithMany()
                        .HasForeignKey("IvaCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Marca", "Marca")
                        .WithMany()
                        .HasForeignKey("MarCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iva");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("comara.Models.Cheque", b =>
                {
                    b.HasOne("comara.Models.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("PagCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("comara.Models.Cliente", b =>
                {
                    b.HasOne("comara.Models.CondicionIVA", "CondicionIVA")
                        .WithMany("Clientes")
                        .HasForeignKey("CliCondicionIVA");

                    b.HasOne("comara.Models.ClienteTipoFormaPago", "TipoFormaPago")
                        .WithMany()
                        .HasForeignKey("CliFormaPago");

                    b.HasOne("comara.Models.TipoDocumento", "TipoDocumento")
                        .WithMany("Clientes")
                        .HasForeignKey("CliTipoDoc");

                    b.Navigation("CondicionIVA");

                    b.Navigation("TipoDocumento");

                    b.Navigation("TipoFormaPago");
                });

            modelBuilder.Entity("comara.Models.Cobro", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("comara.Models.Cotizacion", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("comara.Models.CuentaCorriente", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("comara.Models.DetalleCotizacion", b =>
                {
                    b.HasOne("comara.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArtCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Cotizacion", "Cotizacion")
                        .WithMany("DetalleCotizaciones")
                        .HasForeignKey("CotCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("comara.Models.DetalleVenta", b =>
                {
                    b.HasOne("comara.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArtCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VenCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("comara.Models.MovimientoCaja", b =>
                {
                    b.HasOne("comara.Models.Cheque", "Cheque")
                        .WithMany()
                        .HasForeignKey("ChqCod");

                    b.HasOne("comara.Models.VentaTipoMetodoPago", "TipoMetodoPago")
                        .WithMany()
                        .HasForeignKey("MovMetodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.TipoMovimientoCaja", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("MovTipo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cheque");

                    b.Navigation("TipoMetodoPago");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("comara.Models.Pago", b =>
                {
                    b.HasOne("comara.Models.CuentaCorriente", "CuentaCorriente")
                        .WithMany()
                        .HasForeignKey("CctaCod");

                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.VentaTipoMetodoPago", "TipoMetodoPago")
                        .WithMany()
                        .HasForeignKey("PagMetodoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("CuentaCorriente");

                    b.Navigation("TipoMetodoPago");
                });

            modelBuilder.Entity("comara.Models.Usuario", b =>
                {
                    b.HasOne("comara.Models.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("UsuCreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("comara.Models.Venta", b =>
                {
                    b.HasOne("comara.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CliCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("comara.Models.VentaTipoEstado", "TipoEstado")
                        .WithMany()
                        .HasForeignKey("VenEstado");

                    b.HasOne("comara.Models.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("VenLista");

                    b.HasOne("comara.Models.VentaTipoMetodoPago", "TipoMetodoPago")
                        .WithMany()
                        .HasForeignKey("VenMetodoPago");

                    b.HasOne("comara.Models.TipoComprobante", "TipoComprobante")
                        .WithMany("Ventas")
                        .HasForeignKey("VenTipoCbte");

                    b.Navigation("Cliente");

                    b.Navigation("Lista");

                    b.Navigation("TipoComprobante");

                    b.Navigation("TipoEstado");

                    b.Navigation("TipoMetodoPago");
                });

            modelBuilder.Entity("comara.Models.CondicionIVA", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("comara.Models.Cotizacion", b =>
                {
                    b.Navigation("DetalleCotizaciones");
                });

            modelBuilder.Entity("comara.Models.TipoComprobante", b =>
                {
                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("comara.Models.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("comara.Models.Venta", b =>
                {
                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
